# Generated by Django 5.1.5 on 2025-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Is vegan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Is gluten free')),
                ('is_kosher', models.BooleanField(default=False, verbose_name='Is kosher')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('ingredientes', models.ManyToManyField(to='myapps.ingrediente', verbose_name='Ingredientes')),
            ],
        ),
    ]
